Accessibility updates to RevenueProcessTable, RevenueTypeTable
The following commit should address the following errors:

 Error: The relationship between td elements and their associated th elements is not defined. As this table has multiple levels of th elements, you must use the headers attribute on td elements.
[W3C - H43](https://www.w3.org/TR/WCAG20-TECHS/H43.html)